# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170721_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, to='app.Responsavel'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='app.Aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, to='app.Professor'),
        ),
    ]
