# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170722_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='descritor',
            name='disciplina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Disciplina'),
        ),
        migrations.AddField(
            model_name='descritor',
            name='serie',
            field=models.IntegerField(choices=[(1, '1o. Ano [Fundamental]'), (2, '2o. Ano [Fundamental]'), (3, '3o. Ano [Fundamental]'), (4, '4o. Ano [Fundamental]'), (5, '5o. Ano [Fundamental]'), (6, '6o. Ano [Fundamental]'), (7, '7o. Ano [Fundamental]'), (8, '8o. Ano [Fundamental]'), (9, '9o. Ano [Fundamental]')], default=5),
        ),
    ]
