# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170729_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='resposta',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
