# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170729_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=190, null=True),
        ),
    ]
