# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170731_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
