# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_attachment_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='img_resposta',
            field=models.ImageField(blank=True, null=True, upload_to='resp/%Y/%m/%d/'),
        ),
    ]
