# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170811_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['id']},
        ),
    ]
