# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170821_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Profile')),
                ('nome', models.CharField(max_length=80)),
            ],
            bases=('app.profile',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Professor Assistente'), (3, 'Aluno'), (4, 'Professor'), (5, 'Supervisor'), (6, 'Responsável'), (7, 'Gestor Escolar')], null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='gestor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Gestor'),
        ),
    ]
