# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170823_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nova'), (1, 'Ativa'), (2, 'Arquivada')], default=0),
        ),
    ]
