# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_turma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
