# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_resposta_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoaulasassistidas',
            name='attachment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Attachment'),
        ),
    ]
