# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_historicoaulasassistidas_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='serie_atual',
            field=models.IntegerField(choices=[(1, '1o. Ano [Fundamental]'), (2, '2o. Ano [Fundamental]'), (3, '3o. Ano [Fundamental]'), (4, '4o. Ano [Fundamental]'), (5, '5o. Ano [Fundamental]'), (6, '6o. Ano [Fundamental]'), (7, '7o. Ano [Fundamental]'), (8, '8o. Ano [Fundamental]'), (9, '9o. Ano [Fundamental]')], default=5),
        ),
    ]
