# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171111_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='funcao',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='professor',
            name='matricula',
            field=models.CharField(default='', max_length=30),
        ),
    ]
