# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20171115_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
