# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_aula_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['assunto', 'ordem']},
        ),
    ]
