# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180111_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='classificacao',
            field=models.IntegerField(blank=True, choices=[(1, 'C1'), (2, 'C2'), (3, 'C3'), (4, 'C4')], default=None, null=True),
        ),
    ]
