# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 20:40
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_exercicio_classificacao'),
    ]

    operations = [
        UnaccentExtension()
    ]
