# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie_atual',
            field=models.IntegerField(choices=[(0, 'Debug'), (1, '1o. Ano [Fundamental]'), (2, '2o. Ano [Fundamental]'), (3, '3o. Ano [Fundamental]'), (4, '4o. Ano [Fundamental]'), (5, '5o. Ano [Fundamental]'), (6, '6o. Ano [Fundamental]'), (7, '7o. Ano [Fundamental]'), (8, '8o. Ano [Fundamental]'), (9, '9o. Ano [Fundamental]')], default=5),
        ),
        migrations.AlterField(
            model_name='aula',
            name='serie',
            field=models.IntegerField(choices=[(0, 'Debug'), (1, '1o. Ano [Fundamental]'), (2, '2o. Ano [Fundamental]'), (3, '3o. Ano [Fundamental]'), (4, '4o. Ano [Fundamental]'), (5, '5o. Ano [Fundamental]'), (6, '6o. Ano [Fundamental]'), (7, '7o. Ano [Fundamental]'), (8, '8o. Ano [Fundamental]'), (9, '9o. Ano [Fundamental]')]),
        ),
        migrations.AlterField(
            model_name='descritor',
            name='serie',
            field=models.IntegerField(choices=[(0, 'Debug'), (1, '1o. Ano [Fundamental]'), (2, '2o. Ano [Fundamental]'), (3, '3o. Ano [Fundamental]'), (4, '4o. Ano [Fundamental]'), (5, '5o. Ano [Fundamental]'), (6, '6o. Ano [Fundamental]'), (7, '7o. Ano [Fundamental]'), (8, '8o. Ano [Fundamental]'), (9, '9o. Ano [Fundamental]')], default=5),
        ),
        migrations.AlterField(
            model_name='turma',
            name='serie',
            field=models.IntegerField(choices=[(0, 'Debug'), (1, '1o. Ano [Fundamental]'), (2, '2o. Ano [Fundamental]'), (3, '3o. Ano [Fundamental]'), (4, '4o. Ano [Fundamental]'), (5, '5o. Ano [Fundamental]'), (6, '6o. Ano [Fundamental]'), (7, '7o. Ano [Fundamental]'), (8, '8o. Ano [Fundamental]'), (9, '9o. Ano [Fundamental]')], default=5),
        ),
    ]
