# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20180726_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Escola'),
        ),
    ]
