# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_responsavel_escola'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'ordering': ['id']},
        ),
    ]
