# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180729_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.VimeoThumbnailCache'),
        ),
    ]
