# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20180828_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, help_text='Rua, beco, travessa', max_length=120, null=True)),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('bairro', models.CharField(blank=True, max_length=120, null=True)),
                ('cidade', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
