# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='escola',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Endereco'),
        ),
    ]
