# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_escola_escola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escola',
            old_name='escola',
            new_name='endereco',
        ),
    ]
