# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20181016_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
