# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20181109_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='escolas/%Y/%m/%d/'),
        ),
    ]
