# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_escola_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=500, null=True, unique=True),
        ),
    ]
