# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20181125_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('matutino', 'MAT'), ('vespertino', 'VESP')], default='', max_length=15),
        ),
    ]
