# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-09 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190109_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='letra',
            field=models.CharField(default='', max_length=2),
        ),
    ]
