# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20190207_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='app.Aula'),
        ),
    ]
