# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-08 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20190419_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='token',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='referencia_escola',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
