# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190708_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='codigo_inep',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='codigo_inep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
