# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20190715_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='letra',
            field=models.CharField(default='', max_length=5),
        ),
    ]
