# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20190715_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
