# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_responsavel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='escola',
            field=models.ManyToManyField(blank=True, related_name='professores', to='app.Escola'),
        ),
    ]
