# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20190717_1810'),
    ]

    operations = [

    ]
