# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-22 19:19
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name="master")
    Group.objects.get_or_create(name="assessor")
    Group.objects.get_or_create(name="ddz")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20190726_2115'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
