# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-23 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0055_auto_20190822_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperEnsinoUser',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Profile')),
                ('nome', models.CharField(max_length=80)),
            ],
            bases=('app.profile',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchoolRelationshipManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Escola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='escola',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
