# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20190823_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Professor Assistente'), (3, 'Aluno'), (4, 'Professor'), (5, 'Supervisor'), (6, 'Responsável'), (7, 'Gestor Escolar'), (8, 'Super Ensino User')], null=True),
        ),
    ]
